version: "3.3"

services:
  app:
    container_name: steambans
    restart: always
    environment:
      - PORT=3008
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=
      - MONGO_PWD=
      - MONGO_AUTH_SOURCE=admin
    build: .
    ports: 
      - "3008:3008"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"

 