version: "3.3"

services:
  app:
    container_name: steambans
    restart: always
    environment:
      - PORT=3008
      - MONGO_HOST=localhost
      - MONGO_PORT=27017
      - MONGO_USER=steamBansMonitor
      - MONGO_PWD=
      - MONGO_AUTH_SOURCE=
    build: .
    ports: 
      - "3008:3008"



 